### PR TITLE
[feat] Add BoxOfficeMojo as a source

### PR DESCRIPTION
**Pull request by nwithan8**
## Description

Please include a summary of the changes.

- Add BoxOfficeMojo as a source
- Add `boxofficemojo_latestweekend` as a list
- Add BoxOfficeMojo documentation
- Add boxofficemojo.py module
- Add beautifulsoup dependency
- Tweak name of util method for more generic usage

**Background**:
To no fault of PMM, both [IMDb](https://metamanager.wiki/en/latest/metadata/builders/imdb.html#imdb-chart) and [Trakt](https://metamanager.wiki/en/latest/metadata/builders/trakt.html#trakt-box-office) only display the top 10 movies at the box office on their respective websites. I use these to generate an "At the Box Office" collection, but since the top movies at the box office are typically the newest ones (and therefore the ones unlikely to be available on Plex), this collection is usually a little thin. Funny enough, IMDb owns BoxOfficeMojo and builds its list from BOM, but for some reason only shows the top 10. In an effort to make the collection more accurate to what is actually still in theatres, I'm going to BoxOfficeMojo's ["Latest Weekend"](https://www.boxofficemojo.com/weekend/2023W39/?ref_=bo_hm_rw) list directly and collecting all ~50 movies on there. Thankfully, because of the IMDb-BOM ownership, the page for each movie on BOM links to IMDb, so finding the "imdb_id" was pretty simple.

This uses beautifulsoup for web scraping because BOM doesn't have an official API. The structure is subject to change, but the scraping is actually pretty limited and non-complex, so if it does ever change, it should hopefully be simple to patch it. The main concern is the high number of requests (1 per movie + 2 or 3 others) that this makes to collect all the necessary data, so it's a bit slow. We try to cache the data as much as possible to cut down on I/O times.

### Issues Fixed or Closed

- N/A

## Type of Change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation change (non-code changes affecting only the wiki)
- [ ] Infrastructure change (changes related to the github repo, build process, or the like)

## Checklist

- [x] My code was submitted to the nightly branch of the repository.

### CODE REVIEW

**Comment by YozoraXCII** [comment]
This isn't something that is likely to be merged in its current iteration - boxofficemojo has a lot more options that we would want to include as part of a release (such as specifying a date/week/month/quarter, season, etc).

We have some other work that is more pressing, but we do want to add BoxOfficeMojo support.

**Comment by nwithan8** [comment]
> This isn't something that is likely to be merged in its current iteration - boxofficemojo has a lot more options that we would want to include as part of a release (such as specifying a date/week/month/quarter, season, etc).
> 
> We have some other work that is more pressing, but we do want to add BoxOfficeMojo support.

Bummer, but understood. Anything I can help with specifically?

**Comment by YozoraXCII** [comment]
> > This isn't something that is likely to be merged in its current iteration - boxofficemojo has a lot more options that we would want to include as part of a release (such as specifying a date/week/month/quarter, season, etc).
> > We have some other work that is more pressing, but we do want to add BoxOfficeMojo support.
> 
> Bummer, but understood. Anything I can help with specifically?

This appears to be the exploration that was done into "what could a BoxOfficeMojo builder look like", which may gave you an indication of the kind of things we would hope to add.

[message.txt](https://github.com/meisnate12/Plex-Meta-Manager/files/13492371/message.txt)

**Comment by YozoraXCII** [comment]
@nwithan8 for what it's worth, I ran your changes and ran into the following after it finished processing the 50 movies

```
| Processing 50/50 BoxOfficeMojo movies                                                              |
|                                                                                                    |
| 50 IDs Found                                                                                       |
|                                                                                                    |
| Traceback (most recent call last):                                                                 |
|   File "C:\Users\Yozora\Desktop\Plex-Meta-Manager\plex_meta_manager.py", line 698, in run_collection |
|     builder.filter_and_save_items(builder.gather_ids(method, value))                               |
|   File "C:\Users\Yozora\Desktop\Plex-Meta-Manager\modules\builder.py", line 1931, in filter_and_save_items |
|     input_id, id_type = input_data                                                                 |
|     ^^^^^^^^^^^^^^^^^                                                                              |
| ValueError: too many values to unpack (expected 2)                                                 |
|                                                                                                    |
| Unknown Error: too many values to unpack (expected 2)                                              |
|                                                                                                    |

```

**Pull request closed without merging**
